[package]
name = "conrod_wgpu"
version = "0.70.0"
authors = [
    "mitchmindtree <mitchell.nordine@gmail.com>",
]
keywords = ["ui", "widgets", "gui", "interface", "graphics"]
description = "A crate to assist with rendering conrod UIs via wgpu."
license = "MIT OR Apache-2.0"
readme = "../../README.md"
repository = "https://github.com/pistondevelopers/conrod.git"
homepage = "https://github.com/pistondevelopers/conrod"
categories = ["gui"]
edition = "2018"

[dependencies]
conrod_core = { path = "../../conrod_core", version = "0.70" }
image = "0.23"
winit = "0.22"
cgmath = "0.17"
env_logger = "0.7"
log = "0.4"
wgpu = "0.6"
futures = "0.3"
bytemuck = { version = "1.4", features = [ "derive" ] }
anyhow = "1.0"
find_folder = "0.3"

[dev-dependencies]
conrod_example_shared = { path = "../conrod_example_shared", version = "0.70" }
conrod_winit = { path = "../conrod_winit", version = "0.70" }
find_folder = "0.3"
futures = "0.3"
image = "0.23"
winit = "0.22"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.1"
glob = "0.3"
shaderc = "0.6"
